CREATE TABLE snagging_issues (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    snagging_project_id UUID NOT NULL,
    issue_title VARCHAR(255) NOT NULL,
    issue_description TEXT,
    category VARCHAR(100) NOT NULL CHECK (category IN ('electrical',
    'plumbing',
    'finishing',
    'structural',
    'painting',
    'fixtures',
    'flooring',
    'doors_windows',
    'hvac',
    'landscaping',
    'other')),
    priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low',
    'medium',
    'high',
    'urgent')),
    status VARCHAR(50) DEFAULT 'identified' CHECK (status IN ('identified',
    'assigned',
    'in_progress',
    'resolved',
    'verified',
    'closed')),
    contractor_id UUID,
    assigned_date DATE,
    due_date DATE,
    resolved_date DATE,
    verified_date DATE,
    location_description TEXT,
    estimated_cost DECIMAL(10,2),
    actual_cost DECIMAL(10,2),
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);